version: "2.3"

services:
  worker:
    build:
        context: ./
        dockerfile: ./project/server/Dockerfile_worker
    image: wise-worker
    container_name: wise-eccv-optim-worker
    ports:
      - 8600:8600
    volumes:
      - ./worker/imgs_received:/usr/src/app/worker/img_received
      - ./worker/result:/usr/src/app/worker/result