FROM pytorch/pytorch:1.12.0-cuda11.3-cudnn8-runtime

WORKDIR /usr/app
ADD worker/requirements.txt .
RUN pip install -r requirements.txt

ADD wise .

WORKDIR /usr/app/worker
ADD  worker/serve.py .

EXPOSE 8600

CMD ["python", "serve.py"] 